# Generated by Django 5.2.14 on 2026-05-25 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departmentroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomfacility',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '予約作成'), ('update', '予約変更'), ('cancel', '予約キャンセル'), ('move', '予約移動')], max_length=20, verbose_name='操作種別')),
                ('room_name', models.CharField(max_length=100, verbose_name='会議室名')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('start_at', models.DateTimeField(verbose_name='開始日時')),
                ('end_at', models.DateTimeField(verbose_name='終了日時')),
                ('detail', models.TextField(blank=True, verbose_name='変更内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='reservations.reservation', verbose_name='予約')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': '操作ログ',
                'verbose_name_plural': '操作ログ',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
