"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)s=wy#0ecpfx92^f^m8d-fy+@rzh+^(o7um4t$i1!3twyo+krm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'tko9.bold-rooms-reserve.com',
    '18.177.208.167',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "reservations",
    "accounts",
    "admin_panel",
    "rooms",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 実際のログイン画面URL
LOGIN_URL = "/accounts/login/"

# ログイン成功後のリダイレクト先（会議室の一覧画面）
LOGIN_REDIRECT_URL = "/reservations/timeline/"

# ログアウト後のリダイレクト先
LOGOUT_REDIRECT_URL = "/accounts/login/"

# ユーザーモデル
AUTH_USER_MODEL = "accounts.User"

# Google OAuth 2.0
GOOGLE_CLIENT_ID     = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI  = os.environ.get(
    'GOOGLE_REDIRECT_URI',
    'http://localhost:8000/reservations/auth/google/callback/'
)
GOOGLE_CALENDAR_SCOPES = ['https://www.googleapis.com/auth/calendar.events']

# INSTALLED_APPS に追加（未追加の場合）
# 'rest_framework',

# qq .env ファイル（プロジェクトルートに作成）qqqqqqqqqqqqqqqqq
# GOOGLE_CLIENT_ID=<Google Cloud Console で取得した値>
# GOOGLE_CLIENT_SECRET=<同上>
# GOOGLE_REDIRECT_URI=http://localhost:8000/reservations/auth/google/callback/

# qq Google Cloud Console での設定手順 qqqqqqqqqqqqqqqqqqqqqqq
# 1. https://console.cloud.google.com/ にアクセス
# 2. 「APIとサービス」→「認証情報」→「OAuthクライアントIDを作成」
# 3. アプリケーションの種類：「ウェブアプリケーション」を選択
# 4. 承認済みリダイレクトURIに追加：
#    http://localhost:8000/reservations/auth/google/callback/（開発用）
#    https://yourdomain.com/reservations/auth/google/callback/（本番用）
# 5. 「Google Calendar API」を有効化（「ライブラリ」から検索して有効化）
# 6. クライアントID・シークレットを .env に記載

# qq python-dotenv で .env を読み込む（manage.py と同階層に.env）q
# pip install python-dotenv
# settings.py の先頭に追加:
# from dotenv import load_dotenv
# load_dotenv()
CSRF_TRUSTED_ORIGINS = [
    'https://tko9.bold-rooms-reserve.com',  # 新しいHTTPSのURLをスキーム付きで許可
]